name: 'My Awesome list'
description: 'Generate awesome list from user starred repositories'
branding:
  icon: align-justify
  color: yellow
inputs:
  github-token:
    description: 'Github token'
    required: true
  api-token:
    description: 'Personal API Token'
    required: true
  github-name:
    description: 'Name shown in the commit'
  github-email:
    description: 'Email shown in the commit'
runs:
  using: 'node12'
  main: 'index.js'
