name: 'My Awesome list'
description: 'Generate awesome list from user starred repositories'
inputs:
  github-token:
    description: 'Github token'
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'index.js'
