name: 'My Awesome list'
description: 'Generate awesome list from user starred repositories'
branding:
  icon: align-justify
  color: yellow
inputs:
  github-token:
    description: 'Github token'
    required: true
  api-token:
    description: 'Personal API Token'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
